/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d869a99c-651d-4bdf-bd00-cf9940a06cca",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_33Cje5Vm2",
    "aws_user_pools_web_client_id": "4ggfismiu90o5vo3lk0qgg4k89",
    "oauth": {},
    "aws_user_files_s3_bucket": "tekmentorappsync502b8e1688c2493b99ee4fa758f5b7f212802-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://m5e7g5ik65asbnzxrgzmkkzcvi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
